@isTest
private class OperatorTest {
    
    ///////////////////////insert testing/////////////////////////////////////
    
    public static testmethod void callTestData(){
    test.starttest();
        Operator se1 = Operator.EQUALS;
        Operator se2 = Operator.NOT_EQUALS;
        Operator se3 = Operator.LESS_THAN;
        Operator se4 = Operator.LESS_THAN_OR_EQUAL_TO;
        Operator se5 = Operator.GREATER_THAN;
        Operator se6 = Operator.GREATER_THAN_OR_EQUAL_TO;
        Operator se7 = Operator.LIKEX;
    test.stoptest();
}
}