/**********************************************************************
Name:  PartPrice_Wrapper_Class
Copyright ? 2016  Tavant Technology Inc
==============================================================
===============================================================
Purpose: use for fatching price through webservice                                                                                                                    
===============================================================
===============================================================
History                                                            
-------                                                            
VERSION     AUTHOR            DATE            DETAIL                         FEATURES/CSR/TTP
   1.0 -    Aditya         19/11/2016      INITIAL DEVELOPMENT            
***********************************************************************/

public class PartPrice_Wrapper_Class{

 public class ToType {
    public String To;
    private String[] To_type_info = new String[]{'To','urn:schemas-qad-com:xml-services:common',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://www.w3.org/2005/08/addressing','true','true'};
    private String[] field_order_type_info = new String[]{'To'};
    }
    

    }