/*******************************************************************
    Purpose: Wrapper class to store the apiname and value for dynamic dml                                                     
    Parameters: N/A
    Returns: void
    Throws [Exceptions]: N/A                                                         
    ********************************************************************/
    global with sharing class ServiceCampaignWrapper{
        global String apiName {get;set;}
        global String value {get;set;}
    
    }